# syntax=docker/dockerfile:1
FROM golang:1.20-alpine  AS base
WORKDIR /src    
COPY . .                 
RUN go env -w GOPROXY=https://goproxy.cn,direct  
# RUN go mod download -x

FROM base AS build-client
RUN --mount=type=bind,source=,target=. \ 
    go build -o /bin/client ./cmd/client

FROM base AS build-server
RUN --mount=type=bind,source=,target=. \ 
go build -o /bin/server ./cmd/server

FROM scratch AS client
COPY --from=build-client /bin/client /bin/
ENTRYPOINT [ "/bin/client" ]

FROM scratch AS server
COPY --from=build-server /bin/server /bin/
ENTRYPOINT [ "/bin/server" ]